//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dub.Web.Mvc.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager(typeof(Resources));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось подтвердить телефон.
        /// </summary>
        public static string FailedToVerifyPhone {
            get {
                return ResourceManager.GetString("FailedToVerifyPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рассмотрено.
        /// </summary>
        public static string FieldAcceptedBy {
            get {
                return ResourceManager.GetString("FieldAcceptedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата рассмотрения.
        /// </summary>
        public static string FieldAcceptedDate {
            get {
                return ResourceManager.GetString("FieldAcceptedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Адрес.
        /// </summary>
        public static string FieldAddress {
            get {
                return ResourceManager.GetString("FieldAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество исследовательских центров.
        /// </summary>
        public static string FieldCentersQty {
            get {
                return ResourceManager.GetString("FieldCentersQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменивший пользователь.
        /// </summary>
        public static string FieldChangedBy {
            get {
                return ResourceManager.GetString("FieldChangedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата изменения.
        /// </summary>
        public static string FieldChangedDate {
            get {
                return ResourceManager.GetString("FieldChangedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Описание изменений.
        /// </summary>
        public static string FieldChangeDescription {
            get {
                return ResourceManager.GetString("FieldChangeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Город.
        /// </summary>
        public static string FieldCity {
            get {
                return ResourceManager.GetString("FieldCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Клиент.
        /// </summary>
        public static string FieldClient {
            get {
                return ResourceManager.GetString("FieldClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Код.
        /// </summary>
        public static string FieldCode {
            get {
                return ResourceManager.GetString("FieldCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Компания.
        /// </summary>
        public static string FieldCompany {
            get {
                return ResourceManager.GetString("FieldCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название компании.
        /// </summary>
        public static string FieldCompanyName {
            get {
                return ResourceManager.GetString("FieldCompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтвердите пароль.
        /// </summary>
        public static string FieldConfirmPassword {
            get {
                return ResourceManager.GetString("FieldConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Контактное лицо.
        /// </summary>
        public static string FieldContactPerson {
            get {
                return ResourceManager.GetString("FieldContactPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Продолжить редактирование заявки после ее создания?.
        /// </summary>
        public static string FieldContinuteToEditPage {
            get {
                return ResourceManager.GetString("FieldContinuteToEditPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создано.
        /// </summary>
        public static string FieldCreatedBy {
            get {
                return ResourceManager.GetString("FieldCreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата создания.
        /// </summary>
        public static string FieldCreatedDate {
            get {
                return ResourceManager.GetString("FieldCreatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string FieldEmail {
            get {
                return ResourceManager.GetString("FieldEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Факс.
        /// </summary>
        public static string FieldFax {
            get {
                return ResourceManager.GetString("FieldFax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя файла.
        /// </summary>
        public static string FieldFileName {
            get {
                return ResourceManager.GetString("FieldFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя.
        /// </summary>
        public static string FieldFirstName {
            get {
                return ResourceManager.GetString("FieldFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Полное имя.
        /// </summary>
        public static string FieldFullName {
            get {
                return ResourceManager.GetString("FieldFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Код.
        /// </summary>
        public static string FieldId {
            get {
                return ResourceManager.GetString("FieldId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фамилия.
        /// </summary>
        public static string FieldLastName {
            get {
                return ResourceManager.GetString("FieldLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Участники.
        /// </summary>
        public static string FieldMembers {
            get {
                return ResourceManager.GetString("FieldMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сообщение.
        /// </summary>
        public static string FieldMessage {
            get {
                return ResourceManager.GetString("FieldMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата изменения.
        /// </summary>
        public static string FieldModifiedDate {
            get {
                return ResourceManager.GetString("FieldModifiedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название.
        /// </summary>
        public static string FieldName {
            get {
                return ResourceManager.GetString("FieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заметки.
        /// </summary>
        public static string FieldNotes {
            get {
                return ResourceManager.GetString("FieldNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Код объекта.
        /// </summary>
        public static string FieldObjectId {
            get {
                return ResourceManager.GetString("FieldObjectId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип объекта.
        /// </summary>
        public static string FieldObjectType {
            get {
                return ResourceManager.GetString("FieldObjectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль.
        /// </summary>
        public static string FieldPassword {
            get {
                return ResourceManager.GetString("FieldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отчество.
        /// </summary>
        public static string FieldPatronymicName {
            get {
                return ResourceManager.GetString("FieldPatronymicName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Телефон.
        /// </summary>
        public static string FieldPhone {
            get {
                return ResourceManager.GetString("FieldPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запомнить меня?.
        /// </summary>
        public static string FieldRememberMe {
            get {
                return ResourceManager.GetString("FieldRememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запомнить данный браузер?.
        /// </summary>
        public static string FieldRememberThisBrowser {
            get {
                return ResourceManager.GetString("FieldRememberThisBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Роли.
        /// </summary>
        public static string FieldRoles {
            get {
                return ResourceManager.GetString("FieldRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статус.
        /// </summary>
        public static string FieldStatus {
            get {
                return ResourceManager.GetString("FieldStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название.
        /// </summary>
        public static string FieldTitle {
            get {
                return ResourceManager.GetString("FieldTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Двух-факторная аутентификация.
        /// </summary>
        public static string FieldTwoFactorAuthentication {
            get {
                return ResourceManager.GetString("FieldTwoFactorAuthentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователь.
        /// </summary>
        public static string FieldUserName {
            get {
                return ResourceManager.GetString("FieldUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Справка.
        /// </summary>
        public static string HelpPopupHeader {
            get {
                return ResourceManager.GetString("HelpPopupHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неудачная попытка входа..
        /// </summary>
        public static string InvalidLoginAttempt {
            get {
                return ResourceManager.GetString("InvalidLoginAttempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверный код..
        /// </summary>
        public static string InvalidVerificationCode {
            get {
                return ResourceManager.GetString("InvalidVerificationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка локализации {0}. Не удается найти свойство {2} у типа {1}.
        /// </summary>
        public static string LocalizationFailed {
            get {
                return ResourceManager.GetString("LocalizationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваш пароль был изменен..
        /// </summary>
        public static string PasswordChangedConfirmation {
            get {
                return ResourceManager.GetString("PasswordChangedConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль и подтверждение пароля отличаются.
        /// </summary>
        public static string ValidationMessageCompare {
            get {
                return ResourceManager.GetString("ValidationMessageCompare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле {0} не является e-mail адресом.
        /// </summary>
        public static string ValidationMessageEmailAddress {
            get {
                return ResourceManager.GetString("ValidationMessageEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле {0} обязательно к заполнению..
        /// </summary>
        public static string ValidationMessageRequired {
            get {
                return ResourceManager.GetString("ValidationMessageRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} должен быть {2} символов в длину..
        /// </summary>
        public static string ValidationMessageStringLength {
            get {
                return ResourceManager.GetString("ValidationMessageStringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Необходимо указать комитет, куда будет отправляться заявка на рассмотрение.
        /// </summary>
        public static string ValidationMessageSubmissionCommitteeRequired {
            get {
                return ResourceManager.GetString("ValidationMessageSubmissionCommitteeRequired", resourceCulture);
            }
        }
    }
}
